import { config } from "dotenv";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { exercises } from "./schema/exercise-lib";

// Load .env from monorepo root only if DATABASE_URL not already set (e.g., in CI)
if (!process.env.DATABASE_URL) {
  config({ path: "../../.env" });
}

const client = postgres(process.env.DATABASE_URL!);
const db = drizzle(client);

type ExerciseInsert = typeof exercises.$inferInsert;

export const exerciseSeedData: ExerciseInsert[] = [
  // ============ SQUAT PATTERNS ============
  {
    id: "barbell-back-squat",
    name: "Barbell Back Squat",
    aliases: ["Back Squat", "High Bar Squat", "Low Bar Squat"],
    equipment: ["barbell", "squat_rack"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core", "lower_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "front-squat",
    name: "Front Squat",
    aliases: ["Barbell Front Squat"],
    equipment: ["barbell", "squat_rack"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "core"],
    secondaryMuscles: ["glutes", "upper_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "advanced",
    constraints: ["requires_mobility"],
  },
  {
    id: "goblet-squat",
    name: "Goblet Squat",
    aliases: ["Kettlebell Goblet Squat", "Dumbbell Goblet Squat"],
    equipment: ["kettlebell"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "leg-press",
    name: "Leg Press",
    aliases: ["45 Degree Leg Press", "Machine Leg Press"],
    equipment: ["machine"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    aliases: ["Machine Hack Squat"],
    equipment: ["machine"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "dumbbell-squat",
    name: "Dumbbell Squat",
    aliases: ["DB Squat"],
    equipment: ["dumbbell"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ HINGE PATTERNS ============
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    aliases: ["Deadlift", "Barbell Deadlift"],
    equipment: ["barbell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes", "lower_back"],
    secondaryMuscles: ["quads", "traps", "forearms", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    aliases: ["RDL", "Stiff Leg Deadlift"],
    equipment: ["barbell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "dumbbell-rdl",
    name: "Dumbbell Romanian Deadlift",
    aliases: ["DB RDL", "Dumbbell Stiff Leg Deadlift"],
    equipment: ["dumbbell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap Bar Deadlift",
    aliases: ["Hex Bar Deadlift"],
    equipment: ["trap_bar"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["quads", "hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "traps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlift",
    aliases: ["Wide Stance Deadlift"],
    equipment: ["barbell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes", "quads", "hamstrings"],
    secondaryMuscles: ["adductors", "lower_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: ["requires_mobility"],
  },
  {
    id: "kettlebell-swing",
    name: "Kettlebell Swing",
    aliases: ["KB Swing", "Russian Swing"],
    equipment: ["kettlebell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["core", "shoulders"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "good-morning",
    name: "Good Morning",
    aliases: ["Barbell Good Morning"],
    equipment: ["barbell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["hamstrings", "lower_back"],
    secondaryMuscles: ["glutes", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    aliases: ["Barbell Hip Thrust", "Glute Bridge"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ LUNGE PATTERNS ============
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    aliases: ["Forward Lunge", "Dumbbell Walking Lunge"],
    equipment: ["dumbbell"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunge",
    aliases: ["Backward Lunge", "Step Back Lunge"],
    equipment: ["dumbbell"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    aliases: ["Rear Foot Elevated Split Squat", "RFESS"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "barbell-lunge",
    name: "Barbell Lunge",
    aliases: ["Barbell Walking Lunge"],
    equipment: ["barbell"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "step-up",
    name: "Step Up",
    aliases: ["Dumbbell Step Up", "Box Step Up"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ HORIZONTAL PUSH ============
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    aliases: ["Bench Press", "Flat Bench Press"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "dumbbell-bench-press",
    name: "Dumbbell Bench Press",
    aliases: ["DB Bench Press", "Flat DB Press"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "incline-barbell-press",
    name: "Incline Barbell Press",
    aliases: ["Incline Bench Press"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest", "front_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    aliases: ["Incline DB Press"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest", "front_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "push-up",
    name: "Push Up",
    aliases: ["Press Up"],
    equipment: ["bodyweight"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "dip",
    name: "Dip",
    aliases: ["Parallel Bar Dip", "Chest Dip"],
    equipment: ["bodyweight", "dip_station"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    aliases: ["Chest Press Machine"],
    equipment: ["machine"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    aliases: ["Cable Crossover", "Cable Chest Fly"],
    equipment: ["cable"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ VERTICAL PUSH ============
  {
    id: "overhead-press",
    name: "Overhead Press",
    aliases: ["OHP", "Military Press", "Barbell Shoulder Press"],
    equipment: ["barbell"],
    movementPatterns: ["push_vertical"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "dumbbell-shoulder-press",
    name: "Dumbbell Shoulder Press",
    aliases: ["DB Shoulder Press", "Seated DB Press"],
    equipment: ["dumbbell"],
    movementPatterns: ["push_vertical"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "push-press",
    name: "Push Press",
    aliases: ["Barbell Push Press"],
    equipment: ["barbell"],
    movementPatterns: ["push_vertical"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps", "quads", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    aliases: ["Arnold Dumbbell Press"],
    equipment: ["dumbbell"],
    movementPatterns: ["push_vertical"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    aliases: ["Shoulder Press Machine"],
    equipment: ["machine"],
    movementPatterns: ["push_vertical"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ HORIZONTAL PULL ============
  {
    id: "barbell-row",
    name: "Barbell Row",
    aliases: ["Bent Over Row", "BB Row"],
    equipment: ["barbell"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "dumbbell-row",
    name: "Dumbbell Row",
    aliases: ["One Arm Row", "DB Row", "Single Arm Row"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "cable-row",
    name: "Cable Row",
    aliases: ["Seated Cable Row", "Low Row"],
    equipment: ["cable"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    aliases: ["Landmine Row"],
    equipment: ["barbell", "landmine"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "chest-supported-row",
    name: "Chest Supported Row",
    aliases: ["Incline DB Row", "Seal Row"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "pendlay-row",
    name: "Pendlay Row",
    aliases: ["Dead Stop Row"],
    equipment: ["barbell"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts", "lower_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "advanced",
    grip: "pronated",
    constraints: [],
  },

  // ============ VERTICAL PULL ============
  {
    id: "pull-up",
    name: "Pull Up",
    aliases: ["Chin Up", "Overhand Pull Up"],
    equipment: ["bodyweight", "pull_up_bar"],
    movementPatterns: ["pull_vertical"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "mid_back", "rear_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    aliases: ["Cable Pulldown", "Wide Grip Pulldown"],
    equipment: ["cable"],
    movementPatterns: ["pull_vertical"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "mid_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "neutral-grip-pulldown",
    name: "Neutral Grip Pulldown",
    aliases: ["Close Grip Pulldown", "V-Bar Pulldown"],
    equipment: ["cable"],
    movementPatterns: ["pull_vertical"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "mid_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "assisted-pull-up",
    name: "Assisted Pull Up",
    aliases: ["Machine Assisted Pull Up"],
    equipment: ["machine"],
    movementPatterns: ["pull_vertical"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "mid_back"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "pronated",
    constraints: [],
  },

  // ============ CARRY ============
  {
    id: "farmers-walk",
    name: "Farmer's Walk",
    aliases: ["Farmer's Carry", "Loaded Carry"],
    equipment: ["dumbbell"],
    movementPatterns: ["carry"],
    primaryMuscles: ["forearms", "traps"],
    secondaryMuscles: ["core", "quads", "glutes"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "suitcase-carry",
    name: "Suitcase Carry",
    aliases: ["Single Arm Carry"],
    equipment: ["dumbbell"],
    movementPatterns: ["carry"],
    primaryMuscles: ["core", "forearms"],
    secondaryMuscles: ["traps", "obliques"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "trap-bar-carry",
    name: "Trap Bar Carry",
    aliases: ["Hex Bar Carry"],
    equipment: ["trap_bar"],
    movementPatterns: ["carry"],
    primaryMuscles: ["forearms", "traps"],
    secondaryMuscles: ["core", "quads"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ CORE ANTI-MOVEMENT ============
  {
    id: "plank",
    name: "Plank",
    aliases: ["Front Plank", "Forearm Plank"],
    equipment: ["bodyweight"],
    movementPatterns: ["core_anti"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders", "glutes"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    aliases: ["Supine Dead Bug"],
    equipment: ["bodyweight"],
    movementPatterns: ["core_anti"],
    primaryMuscles: ["core"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    aliases: ["Anti-Rotation Press", "Cable Pallof Press"],
    equipment: ["cable"],
    movementPatterns: ["core_anti"],
    primaryMuscles: ["core", "obliques"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    aliases: ["Ab Rollout", "Wheel Rollout"],
    equipment: ["ab_wheel"],
    movementPatterns: ["core_anti"],
    primaryMuscles: ["core"],
    secondaryMuscles: ["lats", "shoulders"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    aliases: ["Hanging Knee Raise"],
    equipment: ["pull_up_bar"],
    movementPatterns: ["core_anti"],
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },

  // ============ UPPER ISOLATION ============
  {
    id: "bicep-curl",
    name: "Bicep Curl",
    aliases: ["Dumbbell Curl", "DB Curl"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "supinated",
    constraints: [],
  },
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    aliases: ["BB Curl", "Standing Barbell Curl"],
    equipment: ["barbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "supinated",
    constraints: [],
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    aliases: ["Neutral Grip Curl"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps", "forearms"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    aliases: ["Cable Pushdown", "Rope Pushdown"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "skull-crusher",
    name: "Skull Crusher",
    aliases: ["Lying Tricep Extension", "French Press"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    aliases: ["Side Raise", "Dumbbell Lateral Raise"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "face-pull",
    name: "Face Pull",
    aliases: ["Cable Face Pull", "Rope Face Pull"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["rear_delts", "mid_back"],
    secondaryMuscles: ["rotator_cuff"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "rear-delt-fly",
    name: "Rear Delt Fly",
    aliases: ["Reverse Fly", "Bent Over Fly"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["mid_back"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "shrug",
    name: "Shrug",
    aliases: ["Dumbbell Shrug", "Barbell Shrug"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["traps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ LOWER ISOLATION ============
  {
    id: "leg-curl",
    name: "Leg Curl",
    aliases: ["Lying Leg Curl", "Hamstring Curl"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    aliases: ["Quad Extension", "Machine Leg Extension"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    aliases: ["Standing Calf Raise", "Machine Calf Raise"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    aliases: ["Bent Knee Calf Raise"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "hip-adduction",
    name: "Hip Adduction",
    aliases: ["Adductor Machine", "Inner Thigh Machine"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["adductors"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "hip-abduction",
    name: "Hip Abduction",
    aliases: ["Abductor Machine", "Outer Thigh Machine"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ SMITH MACHINE ============
  {
    id: "smith-machine-squat",
    name: "Smith Machine Squat",
    aliases: ["Heel Elevated Smith Squat", "Smith Squat"],
    equipment: ["smith_machine"],
    movementPatterns: ["squat"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "smith-incline-press",
    name: "Smith Incline Press",
    aliases: ["Smith Slight Incline Press", "Smith Machine Incline Press"],
    equipment: ["smith_machine", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest", "front_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "pronated",
    constraints: [],
  },

  // ============ ADDITIONAL CHEST ============
  {
    id: "dumbbell-barrel-press",
    name: "Dumbbell Barrel Press",
    aliases: ["Barrel Press", "Squeeze Press"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },

  // ============ ADDITIONAL SHOULDER ============
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raise",
    aliases: ["Machine Side Lateral", "Lateral Raise Machine"],
    equipment: ["machine"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raise",
    aliases: ["Cable Side Lateral", "Single Arm Cable Lateral"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "incline-lateral-raise",
    name: "Incline Lateral Raise",
    aliases: ["Incline Dumbbell Side Lateral", "Incline Side Raise"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "seated-dumbbell-press-hammer",
    name: "Seated Dumbbell Press Hammer Grip",
    aliases: ["Hammer Grip Shoulder Press", "Neutral Grip DB Press"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["push_vertical"],
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },

  // ============ ADDITIONAL BACK ============
  {
    id: "meadows-row",
    name: "Meadows Row",
    aliases: ["John Meadows Row", "Landmine Row Single Arm"],
    equipment: ["barbell", "landmine"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "seated-row-high-elbow",
    name: "Seated Row High Elbow",
    aliases: ["High Elbow Row", "Wide Grip Seated Row"],
    equipment: ["cable"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["mid_back", "rear_delts"],
    secondaryMuscles: ["lats", "biceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "incline-dumbbell-row",
    name: "Incline Dumbbell Row",
    aliases: ["Incline Dumbbell High Elbow Row", "Incline DB Row"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["mid_back", "rear_delts"],
    secondaryMuscles: ["lats", "biceps"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },
  {
    id: "barbell-pullover",
    name: "Barbell Pullover",
    aliases: ["Barbell Pullovers", "Straight Arm Pullover"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["pull_vertical"],
    primaryMuscles: ["lats", "chest"],
    secondaryMuscles: ["triceps", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },

  // ============ ADDITIONAL REAR DELT ============
  {
    id: "rear-delt-barbell-raise",
    name: "Rear Delt Behind The Back Barbell Raise",
    aliases: ["Behind Back Barbell Rear Delt", "Barbell Rear Delt Raise"],
    equipment: ["barbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["mid_back"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    aliases: ["Cable Rear Delt", "Single Arm Cable Rear Delt"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["mid_back"],
    isCompound: false,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "incline-rear-delt-raise",
    name: "Incline Rear Delt Raise",
    aliases: ["Incline Dumbbell Rear Delt Raise", "Prone Rear Delt Fly"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["mid_back"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ ADDITIONAL BICEP ============
  {
    id: "preacher-curl",
    name: "Preacher Curl",
    aliases: ["Dumbbell Preacher Curl", "Preacher Curl Flat Side"],
    equipment: ["dumbbell", "preacher_bench"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: true,
    difficulty: "beginner",
    grip: "supinated",
    constraints: [],
  },
  {
    id: "incline-curl",
    name: "Incline Curl",
    aliases: ["Incline Dumbbell Curl", "Incline Cable Curl"],
    equipment: ["dumbbell", "bench"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "supinated",
    constraints: [],
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    aliases: ["Cable Straight Bar Curl", "Cable Bicep Curl"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "supinated",
    constraints: [],
  },
  {
    id: "ez-bar-curl",
    name: "EZ Bar Curl",
    aliases: ["EZ Curl", "Cambered Bar Curl"],
    equipment: ["ez_bar"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    // Cambered bar = semi-supinated; tag neutral so a no_supinated/neutral_grip_only
    // athlete keeps it (the wrist-friendly bar is the whole point of the EZ bar).
    grip: "neutral",
    constraints: [],
  },

  // ============ ADDITIONAL TRICEP ============
  {
    id: "cable-tricep-extension",
    name: "Cable Tricep Extension",
    aliases: ["Straight Bar Extension", "Cable Tricep Pushdown Bar"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ ADDITIONAL LOWER ============
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    aliases: ["Seated Hamstring Curl"],
    equipment: ["machine"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "glute-rdl",
    name: "Glute RDL",
    aliases: ["Glute Focused RDL", "Glute Romanian Deadlift"],
    equipment: ["dumbbell"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["lower_back", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },

  // ============ MORE CHEST ============
  {
    id: "decline-bench-press",
    name: "Decline Barbell Press",
    aliases: ["Decline Bench Press", "Decline Press"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "machine-fly",
    name: "Machine Fly",
    aliases: ["Pec Deck", "Machine Chest Fly", "Machine Flys"],
    equipment: ["machine"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ MORE BACK ============
  {
    id: "smith-bent-over-row",
    name: "Smith Bent Over Row",
    aliases: ["Smith Row", "Smith Machine Row"],
    equipment: ["smith_machine"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["lats", "mid_back"],
    secondaryMuscles: ["biceps", "rear_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "cable-pullover",
    name: "Cable Pullover",
    aliases: ["Cable Pullovers", "Straight Arm Pulldown"],
    equipment: ["cable"],
    movementPatterns: ["pull_vertical"],
    primaryMuscles: ["lats"],
    secondaryMuscles: ["chest", "triceps"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "lying-cable-rear-delt-row",
    name: "Lying Cable Rear Delt Row",
    aliases: ["Lying Rear Delt Cable Row", "Prone Cable Row"],
    equipment: ["cable", "bench"],
    movementPatterns: ["pull_horizontal"],
    primaryMuscles: ["rear_delts", "mid_back"],
    secondaryMuscles: ["lats"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "intermediate",
    constraints: [],
  },
  {
    id: "hyper-extension",
    name: "Hyper Extension",
    aliases: ["Back Extension", "Hyper Extensions", "45 Degree Back Extension"],
    equipment: ["machine"],
    movementPatterns: ["hinge"],
    primaryMuscles: ["lower_back", "glutes"],
    secondaryMuscles: ["hamstrings"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "barbell-shrug",
    name: "Barbell Shrug",
    aliases: ["Barbell Shrugs", "Wide Grip Shrug", "Smith Shrug"],
    equipment: ["barbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["traps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "pronated",
    constraints: [],
  },

  // ============ MORE SHOULDER ============
  {
    id: "single-arm-dumbbell-rear-delt-raise",
    name: "Single Arm Dumbbell Rear Delt Raise",
    aliases: ["Single Arm Rear Delt Fly", "One Arm Rear Delt Raise"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["mid_back"],
    isCompound: false,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ MORE TRICEP ============
  {
    id: "close-grip-bench-press",
    name: "Close Grip Bench Press",
    aliases: ["Close Grip Press", "CGBP"],
    equipment: ["barbell", "bench"],
    movementPatterns: ["push_horizontal"],
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "intermediate",
    grip: "pronated",
    constraints: [],
  },
  {
    id: "overhead-dumbbell-extension",
    name: "Overhead Dumbbell Extension",
    aliases: ["Single Arm Overhead Dumbbell Extension", "One Arm Tricep Extension"],
    equipment: ["dumbbell"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "cable-french-press",
    name: "Cable French Press",
    aliases: ["Cable Overhead Tricep Extension", "Cable Tricep Press"],
    equipment: ["cable"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ MORE BICEP ============
  {
    id: "reverse-grip-curl",
    name: "Reverse Grip Curl",
    aliases: ["EZ Bar Reverse Grip Curl", "Reverse Curl"],
    equipment: ["ez_bar"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["forearms", "biceps"],
    secondaryMuscles: [],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    // Overhand (reverse) grip loads wrist extension despite the EZ bar — pronated.
    grip: "pronated",
    constraints: [],
  },
  {
    id: "cable-ez-bar-curl",
    name: "Cable EZ Bar Curl",
    aliases: ["Cable Curl EZ Bar", "EZ Bar Cable Curl"],
    equipment: ["cable", "ez_bar"],
    movementPatterns: ["isolation_upper"],
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    grip: "neutral",
    constraints: [],
  },

  // ============ MORE LEGS ============
  {
    id: "dumbbell-split-squat",
    name: "Dumbbell Split Squat",
    aliases: ["Dumbbell Quad Split Squat", "Split Squat"],
    equipment: ["dumbbell"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "smith-reverse-lunge",
    name: "Smith Reverse Lunge",
    aliases: ["Smith Reverse Lunges", "Smith Machine Lunge"],
    equipment: ["smith_machine"],
    movementPatterns: ["lunge"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    isCompound: true,
    isUnilateral: true,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "monster-walk",
    name: "Monster Walk",
    aliases: ["Banded Monster Walk", "Lateral Band Walk"],
    equipment: ["resistance_band"],
    movementPatterns: ["isolation_lower"],
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hip_flexors"],
    isCompound: false,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },

  // ============ CONDITIONING ============
  {
    id: "battle-ropes",
    name: "Battle Ropes",
    aliases: ["Rope Waves", "Battling Ropes"],
    equipment: ["battle_ropes"],
    movementPatterns: ["conditioning"],
    primaryMuscles: ["shoulders", "core"],
    secondaryMuscles: ["forearms", "lats"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    aliases: ["Erg", "Concept 2", "Indoor Rower"],
    equipment: ["cardio_machine"],
    movementPatterns: ["conditioning"],
    primaryMuscles: ["lats", "quads"],
    secondaryMuscles: ["biceps", "hamstrings", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "assault-bike",
    name: "Assault Bike",
    aliases: ["Air Bike", "Fan Bike", "Airdyne"],
    equipment: ["cardio_machine"],
    movementPatterns: ["conditioning"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "shoulders", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
  {
    id: "sled-push",
    name: "Sled Push",
    aliases: ["Prowler Push"],
    equipment: ["sled"],
    movementPatterns: ["conditioning"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["calves", "core"],
    isCompound: true,
    isUnilateral: false,
    difficulty: "beginner",
    constraints: [],
  },
];

async function seed() {
  console.log("Seeding exercise library...");

  try {
    // Clear existing exercises
    await db.delete(exercises);
    console.log("  Cleared existing exercises");

    // Insert all exercises
    await db.insert(exercises).values(exerciseSeedData);
    console.log(`  Inserted ${exerciseSeedData.length} exercises`);

    console.log("Seed completed successfully!");
  } catch (error) {
    console.error("Seed failed:", error);
    throw error;
  } finally {
    await client.end();
  }
}

// Only auto-run when executed directly (e.g. `tsx src/seed.ts`), not when this
// module is imported (e.g. the seed-sanity test imports `exerciseSeedData`).
if (import.meta.url === `file://${process.argv[1]}`) {
  seed();
}
